### ISSUE TITLE
Interactive doc errors

### ISSUE THREAD

**Issue by viebel** [dvdzkwsk/redash#14]
It's wonderful to see klipse on redash!

I've gone over the interactive doc and discovered a couple of errors:

![image](https://cloud.githubusercontent.com/assets/955710/21467830/6d6bd8ac-ca03-11e6-80c1-ebea2f6a49b2.png)

![image](https://cloud.githubusercontent.com/assets/955710/21467874/a3321e6e-ca04-11e6-8dff-e6047ee33ea7.png)

![image](https://cloud.githubusercontent.com/assets/955710/21467881/e0c3de70-ca04-11e6-8b3e-2ae23286ff2e.png)

![image](https://cloud.githubusercontent.com/assets/955710/21467888/283410a4-ca05-11e6-81fe-c563e419e01c.png)

![image](https://cloud.githubusercontent.com/assets/955710/21467892/4a880ae8-ca05-11e6-9eae-57dcd9d42fb3.png)

![image](https://cloud.githubusercontent.com/assets/955710/21467980/6b3e9f1a-ca08-11e6-8310-046d58ddfd92.png)
![image](https://cloud.githubusercontent.com/assets/955710/21467982/7a0de208-ca08-11e6-90b3-a643fc949d30.png)

![image](https://cloud.githubusercontent.com/assets/955710/21467986/8368c750-ca08-11e6-8a09-796d8a994377.png)

![image](https://cloud.githubusercontent.com/assets/955710/21467988/90f089da-ca08-11e6-86a0-853cf6c2ca0c.png)

![image](https://cloud.githubusercontent.com/assets/955710/21467990/9b0dadbc-ca08-11e6-8367-83388c4921d6.png)

**Comment by dvdzkwsk** [comment]
Wow, thank you so much for doing this @viebel, I really appreciate it! This was a huge help and allowed me to quickly fix the most glaring issues, so thank you for that.

I am hoping get some time to improve the UX/UI of the docs after the holidays, and will keep your definitely idea about a documentation generation tool with klipse in mind :).

Closing as resolved with https://github.com/davezuko/redash/commit/a7593cf8af1963041ca1f89602c7e65abc1c5320.

Merry Christmas 🎉 🎄 !
