### ISSUE TITLE
`pipe` throws wrong error with bad parameter

### ISSUE THREAD

**Issue by levithomason** [dvdzkwsk/redash#15]
When passing several functions as arguments to `pipe`:
```js
_.pipe(
  _.keys,
  _.map(x => x)
)([1, 2, 3])
```

You get this error:
```
Invalid argument supplied to `pipe`. The value at index [0] was not a function; what was received was of type: Nil.
```

However, I believe the error should say something like, "The value must be an array" or similar.

**Comment by dvdzkwsk** [comment]
Totally right, this is a misleading error. This is a bigger concern around type checking as a whole. I'm considering producing a dev build that uses something like https://github.com/sanctuary-js/sanctuary-def to automate this for all functions.

Will be creating an issue/milestone for type checking in general. I'd like to get at least flow + sane runtime checking in place before v1.

**Comment by dvdzkwsk** [comment]
Moving all type checks to TypeScript: https://github.com/davezuko/halcyon/tree/feature/typescript.

Will be removing all runtime type checks as a result, since it should be consistent across all functions.
